#!/bin/bash -e

# Collect devices registered by earlier stages (e.g., stage-halpi2-marine)
DEVICES=""
DEVICES_DIR="${WORK_DIR}/gpsd-devices"
if [ -d "${DEVICES_DIR}" ]; then
    for f in "${DEVICES_DIR}"/*; do
        [ -f "$f" ] || continue
        while IFS= read -r device || [ -n "$device" ]; do
            [[ -z "$device" || "$device" =~ ^# ]] && continue
            DEVICES="${DEVICES} ${device}"
        done < "$f"
    done
    rm -rf "${DEVICES_DIR}"
fi
DEVICES="${DEVICES# }"  # Trim leading space

# Use 115200 bps for serial devices (u-blox receivers are configured to this rate)
if [ -n "$DEVICES" ]; then
    GPSD_OPTIONS="-n -s 115200"
else
    GPSD_OPTIONS="-n"
fi

# Generate gpsd configuration
cat > "${ROOTFS_DIR}/etc/default/gpsd" << EOF
# Generated by stage-halos-marine
DEVICES="${DEVICES}"
GPSD_OPTIONS="${GPSD_OPTIONS}"
USBAUTO=true
EOF
